<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;

class CompanySeeder extends Seeder
{
    public function run()
    {
        $companies = [
            ['id' => 1, 'company_name' => 'ABSD'],
            ['id' => 2, 'company_name' => 'AGUNG CITRA TRANSFORMASI'],
            ['id' => 3, 'company_name' => 'AGUNG CONCERN'],
            ['id' => 4, 'company_name' => 'AGUNG LOGISTIC'],
            ['id' => 5, 'company_name' => 'AGUNG TOYOTA'],
            ['id' => 6, 'company_name' => 'AGUNG TRANSINA RAYA'],
            ['id' => 7, 'company_name' => 'ANZON TOYOTA'],
            ['id' => 8, 'company_name' => 'ARIE HUTAGALUNG & PARTNER'],
            ['id' => 9, 'company_name' => 'ARINA TOYOTA'],
            ['id' => 10, 'company_name' => 'ARMADA DAIHATSU DAN ISUZU'],
            ['id' => 11, 'company_name' => 'ARMADA MITSUBISHI DAN SUZUKI'],
            ['id' => 12, 'company_name' => 'ASPERKINDO'],
            ['id' => 13, 'company_name' => 'ASRI MOTOR'],
            ['id' => 14, 'company_name' => 'ASTRIDO TOYOTA'],
            ['id' => 15, 'company_name' => 'AUTO 2000'],
            ['id' => 16, 'company_name' => 'BADAN PEMBINAAN IDEOLOGI PANCASILA'],
            ['id' => 17, 'company_name' => 'BANK BCA'],
            ['id' => 18, 'company_name' => 'BANK BNI'],
            ['id' => 19, 'company_name' => 'BANK MANDIRI'],
            ['id' => 20, 'company_name' => 'BANK PERMATA'],
            ['id' => 21, 'company_name' => 'BEA CUKAI'],
            ['id' => 22, 'company_name' => 'BINTANG DEPALAN GROUP'],
            ['id' => 23, 'company_name' => 'BPODT'],
            ['id' => 24, 'company_name' => 'BRI MULTIFINANCE INDONESIA'],
            ['id' => 25, 'company_name' => 'BUDI JAYA MOTOR'],
            ['id' => 26, 'company_name' => 'CSU LEASING'],
            ['id' => 27, 'company_name' => 'CV GAPURA SURYA'],
            ['id' => 28, 'company_name' => 'DAIKIN AIRCONDITIONING INDONESIA'],
            ['id' => 29, 'company_name' => 'DAUN MAS VENTURA'],
            ['id' => 30, 'company_name' => 'DAYA TOYOTA'],
            ['id' => 31, 'company_name' => 'DELTAMAS TOYOTA'],
            ['id' => 32, 'company_name' => 'DTECH-ENGINEERING'],
            ['id' => 33, 'company_name' => 'DUNEX EXPRESS'],
            ['id' => 34, 'company_name' => 'DUNEX TRANSINDO'],
            ['id' => 35, 'company_name' => 'DUNIA BARUSA'],
            ['id' => 36, 'company_name' => 'DUTA CENDANA TOYOTA'],
            ['id' => 37, 'company_name' => 'EAS LAW OFFICE'],
            ['id' => 38, 'company_name' => 'ECU WORLDWIDE'],
            ['id' => 39, 'company_name' => 'FAMILY MIP'],
            ['id' => 40, 'company_name' => 'GAIA CONSULTANT'],
            ['id' => 41, 'company_name' => 'GAJIKU'],
            ['id' => 42, 'company_name' => 'GMT'],
            ['id' => 43, 'company_name' => 'GRAHA TOYOTA'],
            ['id' => 44, 'company_name' => 'HASJRAT ABADI'],
            ['id' => 45, 'company_name' => 'HYPER MEGA SHIPPING'],
            ['id' => 46, 'company_name' => 'IBD'],
            ['id' => 47, 'company_name' => 'INDOMOBIL BUSSAN TRUCKING'],
            ['id' => 48, 'company_name' => 'INTERCOM TOYOTA'],
            ['id' => 49, 'company_name' => 'ISTANA AGUNG'],
            ['id' => 50, 'company_name' => 'JATIDIRI LOGISTIK'],
            ['id' => 51, 'company_name' => 'JBA'],
            ['id' => 52, 'company_name' => 'JICT'],
            ['id' => 53, 'company_name' => 'JNT CARGO'],
            ['id' => 54, 'company_name' => 'KALLA TOYOTA'],
            ['id' => 55, 'company_name' => 'KAP AAJ'],
            ['id' => 56, 'company_name' => 'KEMENTRIAN AGRARIA DAN TATA RUANG'],
            ['id' => 57, 'company_name' => 'KINTO'],
            ['id' => 58, 'company_name' => 'KOJA'],
            ['id' => 59, 'company_name' => 'KOPERASI PEGAWAI INDOSAT (KOPINDOSAT)'],
            ['id' => 60, 'company_name' => 'KRIDA TOYOTA'],
            ['id' => 61, 'company_name' => 'KUEHNE NAGEL INDONESIA'],
            ['id' => 62, 'company_name' => 'LIEK MOTOR'],
            ['id' => 63, 'company_name' => 'MIMOSA PUTRA ABADI'],
            ['id' => 64, 'company_name' => 'MIOTA'],
            ['id' => 65, 'company_name' => 'NASMOCO TOYOTA'],
            ['id' => 66, 'company_name' => 'NPCT'],
            ['id' => 67, 'company_name' => 'OCBC NISP'],
            ['id' => 68, 'company_name' => 'OTOMAS'],
            ['id' => 69, 'company_name' => 'PATIMBAN PORT INTERNATIONAL'],
            ['id' => 70, 'company_name' => 'PELANGI INTERNATIONAL LOGISTICS'],
            ['id' => 71, 'company_name' => 'PELINDO'],
            ['id' => 72, 'company_name' => 'PERINTIS PERKASA TOYOTA'],
            ['id' => 73, 'company_name' => 'PICT'],
            ['id' => 74, 'company_name' => 'PLAZA TOYOTA'],
            ['id' => 75, 'company_name' => 'PPM MANAJEMEN'],
            ['id' => 76, 'company_name' => 'PRABU PENDAWA MOTOR'],
            ['id' => 77, 'company_name' => 'PT ARISTA GROUP'],
            ['id' => 78, 'company_name' => 'PT BUMI SENTOSA DWI AGUNG'],
            ['id' => 79, 'company_name' => 'PT KREASI SEMESTA RAYA'],
            ['id' => 80, 'company_name' => 'PT TERANG DUNIA INTERNUSA (UNITED E-BIKE)'],
            ['id' => 81, 'company_name' => 'PT TRIMEGAH AUTO PLAZA'],
            ['id' => 82, 'company_name' => 'PT VISERO ANUGERAH'],
            ['id' => 83, 'company_name' => 'PT. ABSOLUT SERVICE NUSANTARA'],
            ['id' => 84, 'company_name' => 'PT. ADI SARANA ARMADA, TBK'],
            ['id' => 85, 'company_name' => 'PT. ADIRA DINAMIKA MULTI FINANCE'],
            ['id' => 86, 'company_name' => 'PT. AGUNG MULIA JAYA MOTOR (AKSESORIS)'],
            ['id' => 87, 'company_name' => 'PT. AGUNG SOLUSI TRANS'],
            ['id' => 88, 'company_name' => 'PT. ANGKUTAN LOGISTICS PRIMA'],
            ['id' => 89, 'company_name' => 'PT. ARDECO'],
            ['id' => 90, 'company_name' => 'PT. ARISTA GROUP'],
            ['id' => 91, 'company_name' => 'PT. ASTRA CREDIT COMPANY'],
            ['id' => 92, 'company_name' => 'PT. ASTRA INTERNATIONAL'],
            ['id' => 93, 'company_name' => 'PT. ASURANSI ASTRA BUANA'],
            ['id' => 94, 'company_name' => 'PT. ASURANSI RAMAYANA'],
            ['id' => 95, 'company_name' => 'PT. ASURANSI SIMAS'],
            ['id' => 96, 'company_name' => 'PT. ASURANSI SOMPO INDONESIA'],
            ['id' => 97, 'company_name' => 'PT. AUTOINDO PRATAMA'],
            ['id' => 98, 'company_name' => 'PT. BAHANA SELARAS ALAM'],
            ['id' => 99, 'company_name' => 'PT. BANK RAKYAT INDONESIA (PERSERO) Tbk.'],
            ['id' => 100, 'company_name' => 'PT. BANK SYARIAH INDONESIA'],
            ['id' => 101, 'company_name' => 'PT. BCA MULTIFINANCE'],
            ['id' => 102, 'company_name' => 'PT. BRINGIN GIGANTARA'],
            ['id' => 103, 'company_name' => 'PT. BUANA FINANCE'],
            ['id' => 104, 'company_name' => 'PT. CIPTA LAKSANA ARMADA SELARAS'],
            ['id' => 105, 'company_name' => 'PT. CITRA NUSANTARA GEMILANG'],
            ['id' => 106, 'company_name' => 'PT. COCA - COLA'],
            ['id' => 107, 'company_name' => 'PT. CSM CORPORATAMA'],
            ['id' => 108, 'company_name' => 'PT. DAGANGAN KARYA INDONESIA'],
            ['id' => 109, 'company_name' => 'PT. DIARYFOOD INTERNUSA'],
            ['id' => 110, 'company_name' => 'PT. FORSCH AUTOCHEM INDONESIA'],
            ['id' => 111, 'company_name' => 'PT. GARUDA FOOD'],
            ['id' => 112, 'company_name' => 'PT. GRAHA SEGARA'],
            ['id' => 113, 'company_name' => 'PT. GUNUNG SLAMAT'],
            ['id' => 114, 'company_name' => 'PT. HALEYORA POWERINDO'],
            ['id' => 115, 'company_name' => 'PT. INFRATECH INDONESIA'],
            ['id' => 116, 'company_name' => 'PT. JASA RAHARJA'],
            ['id' => 117, 'company_name' => 'PT. KA PROPERTI MANAGEMENT'],
            ['id' => 118, 'company_name' => 'PT. KABULINCO JAYA'],
            ['id' => 119, 'company_name' => 'PT. KASIH SUMBER UTAMA'],
            ['id' => 120, 'company_name' => 'PT. KREASI SEMESTA MEGA (OTOGARD)'],
            ['id' => 121, 'company_name' => 'PT. LAUTAN AIR INDONESIA'],
            ['id' => 122, 'company_name' => 'PT. MAHIZA KARYA MANDIRI'],
            ['id' => 123, 'company_name' => 'PT. MANDIRI ANUGRAH PRADANA (PART)'],
            ['id' => 124, 'company_name' => 'PT. MANDIRI TUNAS FINANCE'],
            ['id' => 125, 'company_name' => 'PT. MARSK'],
            ['id' => 126, 'company_name' => 'PT. MAYBANK'],
            ['id' => 127, 'company_name' => 'PT. MAYBANK FINANCE'],
            ['id' => 128, 'company_name' => 'PT. MAYORA GROUP'],
            ['id' => 129, 'company_name' => 'PT. MEDIA TELEVISI INDONESIA'],
            ['id' => 130, 'company_name' => 'PT. MITRA KARSA UTAMA'],
            ['id' => 131, 'company_name' => 'PT. MITRA PINASTHIKA MUSTIKA'],
            ['id' => 132, 'company_name' => 'PT. MITSUBISHI MOTORS KRAMAYUDHA'],
            ['id' => 133, 'company_name' => 'PT. MULTI KARYA TECHNINDO'],
            ['id' => 134, 'company_name' => 'PT. MULTIDAYA TEKNOLOGI INDONESIA'],
            ['id' => 135, 'company_name' => 'PT. NAIGAI TRANS LINE INDONESIA'],
            ['id' => 136, 'company_name' => 'PT. NUSANTARA EKSPRESS'],
            ['id' => 137, 'company_name' => 'PT. OTO MULTIARTHA'],
            ['id' => 138, 'company_name' => 'PT. PARAMITA BANINDO'],
            ['id' => 139, 'company_name' => 'PT. PENJAMIN INFRASTRUKTUR INFONESIA'],
            ['id' => 140, 'company_name' => 'PT. PESONNA OPTIMA JASA'],
            ['id' => 141, 'company_name' => 'PT. PRAGER KENCANA'],
            ['id' => 142, 'company_name' => 'PT. PRASETIYA MULYA ELI'],
            ['id' => 143, 'company_name' => 'PT. PRATAMA MITRA SEJATI'],
            ['id' => 144, 'company_name' => 'PT. PRATAMA SETIA MANDIRI (OLI)'],
            ['id' => 145, 'company_name' => 'PT. PRIMA ARMADA RAYA'],
            ['id' => 146, 'company_name' => 'PT. PUSAKA PRIMA TRANSPORT (BLUEBIRD GROUP)'],
            ['id' => 147, 'company_name' => 'PT. RHEETAU CIPTA ENERGY'],
            ['id' => 148, 'company_name' => 'PT. SARDANA INDAH BERLIAN MOTOR'],
            ['id' => 149, 'company_name' => 'PT. SERASI AUTORAYA (TRAC)'],
            ['id' => 150, 'company_name' => 'PT. SINGGAR'],
            ['id' => 151, 'company_name' => 'PT. SURYA NUSANTARA SENTOSA'],
            ['id' => 152, 'company_name' => 'PT. SURYA SUDECO'],
            ['id' => 153, 'company_name' => 'PT. TOYOTA ASTRA FINANCIAL SERVICES'],
            ['id' => 154, 'company_name' => 'PT. TOYOTA ASTRA MOTOR'],
            ['id' => 155, 'company_name' => 'PT. TOYOTA LOGISTRA PINGLOKA INDONESIA'],
            ['id' => 156, 'company_name' => 'PT. TRANSMO AGUNG PERGATA'],
            ['id' => 157, 'company_name' => 'PT. TRIARYANI'],
            ['id' => 158, 'company_name' => 'PT. TRIPATRA'],
            ['id' => 159, 'company_name' => 'PT. TRIPLE EGLOBAL TRANSFORMASI'],
            ['id' => 160, 'company_name' => 'PT. TRUE FINANCE'],
            ['id' => 161, 'company_name' => 'PT. TUJUH SEMBILAN JAYA'],
            ['id' => 162, 'company_name' => 'PT. UG ARTHA'],
            ['id' => 163, 'company_name' => 'PT. ULTRAJAYA MILK INDUSTRIES TBK'],
            ['id' => 164, 'company_name' => 'PT. WAHANA OTOMITRA MULTIARTHA'],
            ['id' => 165, 'company_name' => 'PT. WIJAYA KARYA'],
            ['id' => 166, 'company_name' => 'PT. YCH INDONESIA'],
            ['id' => 167, 'company_name' => 'PUSAT PENGELOLAAN KOMP. KEMAYORAN'],
            ['id' => 168, 'company_name' => 'REETHAU'],
            ['id' => 169, 'company_name' => 'REJEKI TOYOTA'],
            ['id' => 170, 'company_name' => 'RELASI DRP'],
            ['id' => 171, 'company_name' => 'RELASI HMB'],
            ['id' => 172, 'company_name' => 'RELASI MDP'],
            ['id' => 173, 'company_name' => 'RELASI MIP'],
            ['id' => 174, 'company_name' => 'RELASI MIP - CC 74'],
            ['id' => 175, 'company_name' => 'RELASI MIP - UI 75'],
            ['id' => 176, 'company_name' => 'RELASI MRP'],
            ['id' => 177, 'company_name' => 'RITASE'],
            ['id' => 178, 'company_name' => 'SALINDO BERLIAN MOTOR'],
            ['id' => 179, 'company_name' => 'SELAMAT TOYOTA'],
            ['id' => 180, 'company_name' => 'SETIAJAYA TOYOTA'],
            ['id' => 181, 'company_name' => 'SINAR MAS TOYOTA'],
            ['id' => 182, 'company_name' => 'SINAR SURI'],
            ['id' => 183, 'company_name' => 'SINERGI SUKSES LOGISTIK'],
            ['id' => 184, 'company_name' => 'SRIKREASI'],
            ['id' => 185, 'company_name' => 'SUCCOR SECURITAS'],
            ['id' => 186, 'company_name' => 'SUMBER HARAPAN'],
            ['id' => 187, 'company_name' => 'SUMITOMO CORPORATION'],
            ['id' => 188, 'company_name' => 'SUTANINDO TOYOTA'],
            ['id' => 189, 'company_name' => 'TAFS'],
            ['id' => 190, 'company_name' => 'TMMIN'],
            ['id' => 191, 'company_name' => 'TOYOFUJI SERASI INDONESIA'],
            ['id' => 192, 'company_name' => 'TOYOTA KARTIKA SARI'],
            ['id' => 193, 'company_name' => 'TOYOTA MERDEKA MOTOR'],
            ['id' => 194, 'company_name' => 'TOYOTA SURYA INDAH MOTOR'],
            ['id' => 195, 'company_name' => 'TRANS SUMATRA ANADALAN'],
            ['id' => 196, 'company_name' => 'TUGU'],
            ['id' => 197, 'company_name' => 'TUNAS AUTO GRAHA TOYOTA'],
            ['id' => 198, 'company_name' => 'TUNAS TOYOTA'],
            ['id' => 199, 'company_name' => 'WIJAYA TOYOTA'],
            ['id' => 200, 'company_name' => 'WIRA MEGAH TOYOTA'],
        ];

        foreach ($companies as $company) {
            \Log::info('Company data before updateOrCreate', ['company' => $company]);
            Company::updateOrCreate(['id' => $company['id']], $company);
            \Log::info('Company data after updateOrCreate', ['company' => $company]);
        }
        
    }
}
